# base image which contains node related to node modules
FROM  node:alpine


# specifying working directory
WORKDIR /app

# Copying package.json to docker filesystem
COPY ./package.json .

# Installed dependecies
RUN npm install

# Copying local files to docker filesystem
# we can remove this when we use volumes but in future if we use docker file to create production docker we do need this so its better to have it.
COPY . .

# command that runs when we create container
CMD ["npm", "start"]